### ISSUE TITLE
Where can I locate mekd.pkl you're using in a streamlit demo? 

### ISSUE THREAD

**Issue by e-ndrus** [awarebayes/RecNN#10]
Hey @awarebayes, amazing project! Trying to run your streamlit demo, but can't locate mekd.pkl. Where can it be downloaded from? Thanks!

**Comment by awarebayes** [comment]
1. All the data I used is here:
https://github.com/awarebayes/recnn-demo/tree/master/app/data

2. Here is a docker repo that sets everything up:
https://github.com/awarebayes/recnn-demo

```
cd ~/Downloads
git clone https://github.com/awarebayes/recnn-demo
cd recnn-demo && sh setup.sh
```

**Comment by e-ndrus** [comment]
Thanks! Worked like charm!
