### ISSUE TITLE
running streamlit_demo but error

### ISSUE THREAD

**Issue by MissYBYue** [awarebayes/RecNN#11]
File of movie_counts.csv is not exist;running streamlit_demo get this error;

**Comment by awarebayes** [comment]
Hi, thanks for your interest

All the data I used is here:
https://github.com/awarebayes/recnn-demo/tree/master/app/data

You can download the data as a zip archive here:
https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/awarebayes/recnn-demo/tree/master/app/data 


 Alternatively here is a docker repo that sets everything up:

https://github.com/awarebayes/recnn-demo


```
cd ~/Downloads
git clone https://github.com/awarebayes/recnn-demo
cd recnn-demo && sh setup.sh
```

**Comment by awarebayes** [comment]
Hello, has it worked out for you? Can I close this issue?

**Comment by MissYBYue** [comment]
of course；thank you------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Mike&amp;nbsp;Watts&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月23日(星期六) 凌晨0:44
收件人:&nbsp;&quot;awarebayes/RecNN&quot;<RecNN@noreply.github.com&gt;;
抄送:&nbsp;&quot;MissYBYue&quot;<453056838@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [awarebayes/RecNN] running streamlit_demo but error (#11)
