### ISSUE TITLE
How is ml20_pca128.pkl embedding generated and how to generate the similar embeddings for ml_1m and ml_100k datasets ?

### ISSUE THREAD

**Issue by honolulu2** [awarebayes/RecNN#12]

**Comment by awarebayes** [comment]
Hi, I am sorry for it taking so long to write back.

All of the embedding generation pipeline can be found there: https://github.com/awarebayes/RecNN/tree/master/examples/0.%20Embeddings%20Generation

Try using the 20M version with the lesser datasets, they probably will work regardless

**Comment by awarebayes** [comment]
Hello, has it worked out for you? I do not like to keep issues opened...

**Comment by ucasiggcas** [comment]
dear，
could you pls try the [Youtube2016](https://dl.acm.org/doi/10.1145/2959100.2959190) or [Youtube2019](https://dl.acm.org/doi/10.1145/3298689.3346997)?

**Comment by awarebayes** [comment]
> dear，
> could you pls try the [Youtube2016](https://dl.acm.org/doi/10.1145/2959100.2959190) or [Youtube2019](https://dl.acm.org/doi/10.1145/3298689.3346997)?

No, not right now at least. Kind of busy to work on it, although you contribution will be welcome. But I had already implemented the REINFORCE algorithm that was developed by google and  tested on the youtube dataset.
