### ISSUE TITLE
Deep Reinforcement Learning based Recommendation with Explicit User-Item Interactions Modeling

### ISSUE THREAD

**Issue by miladfa7** [awarebayes/RecNN#2]
Is this a complete implementation of the paper (Deep Reinforcement Learning based Recommendation with Explicit User-Item Interactions Modeling)?

**Comment by awarebayes** [comment]
Not yet, but the ddpg actor itself is working. Tomorrow I will add regularization and state representation (I deleted it recently for simplicity purposes). The dataset will be available soon. The only thing left from ML20 are the rewards (ratings) and if there are any problems with copyright I will release a tree based solution to generate synthetic ratings. I also don't know about the user embeddings just yet. But I wanted to make it more than just 'code for paper' by adding graph and geometrical learning support as well as overhauling the dataset

**Comment by miladfa7** [comment]
very good 
thanks

**Comment by awarebayes** [comment]
New article released, be sure to check it out: https://towardsdatascience.com/reinforcement-learning-ddpg-and-td3-for-news-recommendation-d3cddec26011

**Comment by miladfa7** [comment]
hi
I am pursuing my master degree in Artificial Intelligence at the University of Zanjan. I am interested in AI in particular Recommendation Systems, and I opted this phenomenal area of AI as a research topic for my master thesis. I have chosen "recommendation system based deep reinforcement learning " as topic my master thesis.

Please if possible, share if you have any ideas in this area.

Thank you
________________________________

**Comment by miladfa7** [comment]
hi
I am pursuing my master degree in Artificial Intelligence at the University of Zanjan. I am interested in AI in particular Recommendation Systems, and I opted this phenomenal area of AI as a research topic for my master thesis. I have chosen "recommendation system based deep reinforcement learning " as topic my master thesis.

Please if possible, share if you have any ideas in this area.

Thank you

________________________________

**Comment by awarebayes** [comment]
Most of the recommender systems use lstm for state representation. What if you use finite item state representation with novel importance sampling algorithms, (i.e.) state is sampled from learning to rank (LambdaRank, RankNet) or some Bayesian based algorithm. 
Lstm is not the best idea for state representation/1D convolution. Wavenets switched to TCNs a while ago: “The fall of RNN / LSTM” by Eugenio Culurciello https://link.medium.com/EoheS55VFZ
P.S. if you happen to implement any of these, please push a commit

**Comment by awarebayes** [comment]
https://trello.com/b/wnor4IZf/recnn

**Comment by miladfa7** [comment]
Hi Dear


What is the roadmap I need to follow to learn deep reinforcement learning?

What is the best course for learning "deep reinforcement learning"?

Thank you for guiding me

________________________________

**Comment by awarebayes** [comment]
Hi there, sweetheart!
I got some cool mentoring in MIPT here in Russia on general Deep Learning in the junior year of high school, but I studied the RL by myself. TBH when I wrote my first article I was not very familiar with Reinforcement Learning, just wanted to do a cool school project and tell about something.
***
Check out Yandexes Practical RL: github.com/yandexdataschool/Practical_RL
They have materials linked in the lesson folder as well as interactive notebooks
***
Read Andrej Karpathy's blog: http://karpathy.github.io/
***
Jonathan Hui has some cool blogposts on general RL: https://medium.com/@jonathan_hui/rl-deep-reinforcement-learning-series-833319a95530
***
You can visit our website: ttps://www.dlschool.org/?lang=en
Or/And fork the repo: https://github.com/DLSchool/dlschool_english

**Comment by miladfa7** [comment]
Thank you very much
Great help❤️🙏
________________________________
