### ISSUE TITLE
Interpreting the recommendation results

### ISSUE THREAD

**Issue by gurkan-yilmaz-kariyer-arge** [awarebayes/RecNN#25]
Hi, i was trying to understand the recommendation results but i could not come up with an explanation.

```
value_net  = recnn.nn.Critic(1290, 128, 256, 54e-2)
policy_net = recnn.nn.Actor(1290, 128, 256, 6e-1)
recommendation = policy_net(state)
value = value_net(state, recommendation)
print(recommendation)
print(value)
```

```
tensor([[ 3.7613, -3.4141,  3.0177,  ..., -4.2616, -3.1591, -0.4270],
        [ 3.7313, -3.1471,  5.0571,  ..., -2.9717, -1.8467, -4.7726],
        [ 1.9474,  1.0796,  6.5727,  ..., -6.5865,  1.0699, -5.3639],
        ...,
        [ 2.6672, -4.2484, -0.3397,  ..., -4.4179, -1.1133, -2.9916],
        [ 5.5805, -4.7790, -4.0367,  ..., -4.2819, -0.4999, -3.0007],
        [-2.6792,  0.4703,  5.4456,  ..., -2.2477,  4.8281, -0.8356]],
       grad_fn=<AddmmBackward>)
tensor([[-0.7228],
        [ 0.6361],
        [-4.5583],
        ...,
        [-3.4151],
        [-2.1304],
        [-6.2599]], grad_fn=<AddmmBackward>)
```

```
>>>print(recommendation.shape)
>>>print(value.shape)
torch.Size([1785, 128])
torch.Size([1785, 1])

```

My question is that what does 1785 represent? Does it represent 1785 movie vectors and does value represent their relevance score? And how can i get the recommended movie id or movie name from these two variables.

**Comment by gurkan-yilmaz-kariyer-arge** [comment]
I was trying to get an output in the following manner:
First give the model a user_id
Then take the recommended N items for that specific user id in the form of 
[
(recommended_item1, score1),
(recommended_item2, score2),
(...)
]

**Comment by awarebayes** [comment]
Hello! Sorry for long reply!
> My question is that what does 1785 represent?
It is your dataset size.
> And how can i get the recommended movie id or movie name from these two variables.
See ranking example in the documentation. Select some of these 1785 actions. Calculate distance from it to all alctions. Find top K closes matches
