### ISSUE TITLE
confused about train

### ISSUE THREAD

**Issue by davidjiangt** [awarebayes/RecNN#4]
In the existing literature, they use agents to explore and then get a model based on the interaction data. But I found that in your code, you use the data directly from the Dataset to train.I was wondering if I didn't understand your code or...

**Comment by awarebayes** [comment]
Maybe you are confusing it with on-policy?
What do you mean by exploring? There is a BCQ section that focuses on RL without exploration on a static dataset using VAEs and sampled actions. Top-K Off-Policy Correction
for a REINFORCE Recommender System (Minmin Chen et al, https://arxiv.org/abs/1812.02353) proposes a correction algorithm:

![Screenshot](https://user-images.githubusercontent.com/42784580/65059184-36341380-d97e-11e9-97e4-ee25ddb76542.png)

> Unlike classical reinforcement learning, our learner does not have
> real-time interactive control of the recommender due to learning
> and infrastructure constraints. In other words, we cannot perform
> online updates to the policy and generate trajectories according to
> the updated policy immediately. Instead we receive logged feedback
> of actions chosen by a historical policy (or a mixture of policies),
> which could have a different distribution over the action space than
> the policy we are updating

I am yet to implement this algo, for now, you can use Batch Constrained Learning instead: https://arxiv.org/abs/1812.02900

**Comment by awarebayes** [comment]
Any update? Do I need to close this issue?

**Comment by davidjiangt** [comment]
Thank you very much for your reply！

**Comment by davidjiangt** [comment]
YES, you can close this issue
