### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm.auto'

### ISSUE THREAD

**Issue by miladfa7** [awarebayes/RecNN#5]
I Run this code : 

```
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
import pickle
import gc
import json
import h5py

from IPython.display import clear_output
import matplotlib.pyplot as plt
%matplotlib inline


# == recnn ==
import sys
sys.path.append("../../")
import recnn

device = torch.device('cuda')
# ---
frame_size = 10
batch_size = 10
embed_dim  = 128
# --- 

tqdm.pandas()
```

Result: 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-372a0f072bd7> in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 from tqdm.auto import tqdm
      4 import pickle
      5 import gc

ModuleNotFoundError: No module named 'tqdm.auto'

**Comment by awarebayes** [comment]
Check this issue: https://github.com/tqdm/tqdm/issues/234

**Comment by awarebayes** [comment]
Alternatively you can go to recnn.data.utils module and manually replace the `progress_apply` with `apply`. 
In this case tqdm.auto will not be needed. Although there will be no log of data loading.

**Comment by miladfa7** [comment]
> Alternatively you can go to recnn.data.utils module and manually replace the `progress_apply` with `apply`.
> In this case tqdm.auto will not be needed. Although there will be no log of data loading.

Thank you very much
