### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled in DDPG.pynb notebook ?

### ISSUE THREAD

**Issue by vaibhav231** [awarebayes/RecNN#9]
for batch in tqdm(env.train_dataloader):
---> 38         loss = ddpg_update(batch, params, step=step)
     39         plotter.log_losses(loss)
     40         step += 1

<ipython-input-19-784b49e8d84d> in ddpg_update(batch, params, learn, step, pin_memory)
     70 def ddpg_update(batch, params, learn=True, step=-1,pin_memory=False):
     71 
---> 72     state, action, reward, next_state, done = recnn.data.get_base_batch(batch)
     73 
     74     # --------------------------------------------------------#

~/recnn/data/utils.py in get_base_batch(batch, device, done)
    219     else:
    220         batch.append(torch.zeros_like(batch['reward']))
--> 221     return [i.to(device) for i in b]
    222 
    223 

~/recnn/data/utils.py in <listcomp>(.0)
    219     else:
    220         batch.append(torch.zeros_like(batch['reward']))
--> 221     return [i.to(device) for i in b]
    222 
    223 

~/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py in _lazy_init()
    160         raise RuntimeError(
    161             "Cannot re-initialize CUDA in forked subprocess. " + msg)
--> 162     _check_driver()
    163     torch._C._cuda_init()
    164     _cudart = _load_cudart()

~/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py in _check_driver()
     73 def _check_driver():
     74     if not hasattr(torch._C, '_cuda_isDriverSufficient'):
---> 75         raise AssertionError("Torch not compiled with CUDA enabled")
     76     if not torch._C._cuda_isDriverSufficient():
     77         if torch._C._cuda_getDriverVersion() == 0:

AssertionError: Torch not compiled with CUDA enabled

**Comment by awarebayes** [comment]
Far as I understand you don't have cuda enabled. Try using device = torch.device("cpu") , it is defined above. Though cuda is highly recommended, if you don't have a GPU, get a free instance over at  Google Colab / Paperspace Gradient:

gradient.paperspace.com,
colab.research.google.com

Try online colab demo I have in readme.md

**Comment by awarebayes** [comment]
Just checked [this colab notebook](https://colab.research.google.com/drive/1xWX4JQvlcx3mizwL4gB0THEyxw6LsXTL), runs fine
